config/routes.rb
Lovemachine::Application.routes.draw do

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"

  namespace :admin do
    root "base#index"
    resources :users
  end

  resources :users
  resources :tags, only: [:show, :index, :create]
  resources :user_tags, only: [:create, :destroy]
  get '', to: 'tags#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root "tags#index"

  resources :tumblr_photos, only: [:index]
  resources :tweets, only: [:index]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged

  has_many :user_tags
  has_many :tags, through: :user_tags

  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end

  # Use a secure password
  has_secure_password

  # Basic validations
  validates :username,:email, presence: true
  validates :username, length: { in: 4..20 }
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 4 }, on: :create
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"

  def loves?(tag)
    tags.include?(tag)
  end

end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_signin!
  
  def index    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only:[
    :edit,
    :update
  ]

  def edit
  end

  def update
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    if @user.update(new_params)
      redirect_to admin_root_path, notice: "Your account was successfully updated."
    else
      flash[:alert] = "Account not updated."
      render :edit
    end
  end

  private

  def set_user
    @user = User.friendly.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  # require sign in
  def require_signin!
    if current_user.nil?
      redirect_to signin_url, alert: "You need to sign in first"
    end
  end
  helper_method :require_signin!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user ? true : false
  end
  helper_method :user_signed_in?

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to(root_path, notice: "You are already signed in.") if current_user 
  end

  def create
    user = User.where(username: params[:signin][:username].strip).first

    if user && user.authenticate(params[:signin][:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_path
    else
      flash[:error] = "Wrong username/password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out."
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: request.subdomain)
  end

  def index
    @tags = if current_user && current_user.tags.any?
      current_user.tags
    else
      Tag.all
    end
  end

  def create
    if @tag = Tag.where(name: params[:tag][:name]).first_or_create
      redirect_to root_url(subdomain: @tag.name)
    end
  end
end

app/controllers/tumblr_photos_controller.rb
class TumblrPhotosController < ApplicationController
  def index
    tumblr_client = Tumblr::Client.new
    photos = tumblr_client.tagged("#{params[:tag]}").select{ |p| p['type'] == 'photo' }

    render json: photos
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = TWITTER_CLIENT.search("##{params[:tag]} -rt").take(50).collect do |tweet|
      {
        'text'     => tweet.text,
        'url'      => tweet.url.to_s,
        'user'     => tweet.user.screen_name,
        'user_pic' => tweet.user.profile_image_url
      }
    end

    render json: @tweets
  end

end

app/controllers/user_tags_controller.rb
class UserTagsController < ApplicationController
  def create
    user_tag = current_user.user_tags.new(tag_id: params[:id])
    if user_tag.save
      redirect_to root_url(subdomain: false)
    end
  end

  def destroy
    user_tag = current_user.user_tags.where(tag_id: params[:id]).first
    if user_tag.destroy
      redirect_to root_url(subdomain: false)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = User.where(username: params[:user][:username].strip).present?
      flash[:notice] = "You already exist, sign in, #{@user.username}"
      redirect_to signin_path
    else
      if @user = User.create(user_params)
        session[:user_id] = @user.id
        flash[:notice] = "Welcome, #{@user.username}"
        redirect_to root_path
      else
        redirect_to back
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Lovemachine"      
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def hashtag_meta(tag_name)
    tag('meta', name: 'hashtag', content: tag_name)
  end

  def love_or_unlove_button(tag)
    if current_user.loves?(tag)
      button_to "unlove", user_tag_path(id: tag.id), method: :delete
    else
      button_to "love", user_tags_path(id: tag.id)
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_tags_helper.rb
module UserTagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/base/index.html.erb
<h1>Admin Zone <small>logged in as <%= current_user.username %></small></h1>

<p><%= link_to "Edit your account", edit_admin_user_path(current_user) %></p>
  

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Edit your account</h1>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_for [:admin, @user], role: "form" do |f| %>
  
    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">    
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
  
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update your account", class: "btn btn-primary" %> - <%= link_to "cancel", admin_root_path %>
      </div>
    </div>
  
    <% end %>
  </div>
</div>

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50390501-1', 'iswhatilove.org');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2014 - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_url(subdomain: false), class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <%= form_for Tag.new, html: { class: "navbar-form navbar-left", role: "search" } do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "Search" %>
        </div>
        <%= f.submit "Submit", class: "btn btn-default" %>
      <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !current_user %>
  <li><%= link_to "Sign in", signin_path %></li>
  <li><%= link_to "Sign up", new_user_path %></li>
<% else %>
  <li><%= link_to "Admin", admin_root_path %></li>
  <li><%= link_to "Sign out", signout_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Lovemachine" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :header %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/analytics' %>

</body>
</html>

app/views/tags/_tag.html.erb
<li>
  <h1><%= link_to tag.name, root_url(subdomain: tag.name) %></h1>
  <% if current_user %>
    <p><%= love_or_unlove_button(tag) %></p>
  <% else %>
  <% end %>
</li>

app/views/tags/_tweet.html.erb
<div class="panel panel-default">
  <span>
    <img class="img-circle" src=<%= tweet[:user_pic] %> height="100" width="100" align="right">
    <h2 class='panel-body text-left'>
      <a href=<%= tweet[:url] %> style='display:inline'><%= tweet[:text] %></a>
    </h2>
    <h4>~ <%= tweet[:user] %></h4>
  </span>
</div>

app/views/tags/index.html.erb
<ul>
  <%= render @tags %>
</ul>

app/views/tags/show.html.erb
<%= content_for(:header) do %>
  <%= hashtag_meta(@tag.name) %>
  <%= javascript_include_tag "instagram-scroll" %>
<% end %>

<h1><%= @tag.name %></h1>
<% if current_user %>
  <p><%= love_or_unlove_button(@tag) %></p>
<% else %>
  <p><%= link_to "Sign in to love", signin_path %></p>
<% end %>

<ul class="nav nav-tabs">
  <li class="active">
    <a href="#instapane" id="instagrams" data-toggle="tab">Instagrams</a>
  </li>
  <li>
    <a href="#twitterpane" id='tweets' data-toggle="tab" data-url="<%= tweets_path(tag: @tag.name) %>">Tweets</a>
  </li>
  <li>
    <a href="#tumblrpane" id='tumbls' data-toggle="tab" data-url="<%= tumblr_photos_path(tag: @tag.name) %>">Tumbls</a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="instapane">
    <div id="instas"></div>
  </div>
  <div class="tab-pane fade in" id="twitterpane">
    <div class="panel panel-default">
      <div id="individual_tweets"></div>
    </div>
  </div>
  <div class="tab-pane fade in" id="tumblrpane">
    <div id="tumblr_photos"></div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    return LoadResults();
  });

  $('#tweets').click(function(){
    var tweet_url = $("a#tweets").data("url");
    $.get(tweet_url, function(data){
      $.each(data, function(index, tweet){
        $("#individual_tweets").append(
          "<div class='panel panel-default'> \
            <span> \
              <img class='img-circle' src='" + tweet.user_pic.scheme + "://" + tweet.user_pic.host + tweet.user_pic.path + "' height='100' width='100' align='right'> \
              <h2 class='panel-body text-left'> \
                <a href='" + tweet.url + "' style='display:inline'>" + tweet.text + "</a> \
              </h2> \
              <h4>~ " + tweet.user + "</h4> \
            </span> \
          </div>"
        );
      });
    });
  });

  $('#tumbls').click(function(){
    var tumblr_url = $("a#tumbls").data("url");
    $.get(tumblr_url, function(data){
      $.each(data, function(index, photo){
        $("#tumblr_photos").append("<img src='" + photo.photos[0].original_size.url + "'>");
      });
    });
  });

</script>

app/views/tweets/index.json.erb
<% @tweets.each do |tweet| %>
  <%= tweet.to_json %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Sign up</h1>

    <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :email,  class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Sign up", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>

  </div>
</div>